### ISSUE TITLE
Geoportal: refresh facets so that there are no zeros

### ISSUE THREAD

**Issue by valentinedwv** [CINERGI/ProjectIssues#5]
Tom: refresh facets so that there are no zeros
Almost done, it seems. Perhaps use a dummy “all items” category to force refresh.

**Comment by tom2275** [comment]
Fixed this by adding an "if (theCount>0)" to the tree building logic.  If a node has a value of zero, it isn't rendered.

**Comment by izaslavsky** [comment]
looks great!
